### ISSUE TITLE
Unable to communicate with the MPU6000

### ISSUE THREAD

**Issue by Mathijsvb** [Mathijsvb/MulticopterFCS#1]
The last few days I've been trying to communicate with the MPU6000 chip with no success. This chip functions as the acceleromiter and gyro of the flight controller board.

**What I've tried:**

1.  I've tried to communicate with the IC via SPI, but the MISO line remained low. I tried I²C, but no message was acknowledged.
2. I've tried replacing the IC with a new one. This yielded the same results. Do note that the chips did not arrive in their original packaging, so there is a chance that both IC's were reused and thus not as reliable. 

---

**Additional info:**

[![Capture](https://user-images.githubusercontent.com/99826862/184659862-6cedbccb-9bbd-45b8-a207-64f47fbe7046.JPG)](https://user-images.githubusercontent.com/99826862/184659862-6cedbccb-9bbd-45b8-a207-64f47fbe7046.JPG)  
This was recorded using a logic analyser. The first byte send starts with a 1 for MSB to indicate READ and follows with the register address 0x75 which should contain the WHO_AM_I register value which is 0x68 according to the datasheet. The figure shows nothing is returned. Attempting to read from other registers also returend nothing.
Clock frequency is 1 MHz, changing the frequency yields the same results. As for SPI settings: clock polarity is high and data is read on the second edge.

When looking at the board, the solder joints seem fine, but it is hard to judge since the joints are underneath the package. 
Component values were checked and seemed fine.

Here is the schematic used. Signal lines go to the MCU unimpeded.  
[![Capture](https://user-images.githubusercontent.com/99826862/184660398-3d4355f8-4c5f-49b4-8710-578c2d8f419b.JPG)](https://user-images.githubusercontent.com/99826862/184660398-3d4355f8-4c5f-49b4-8710-578c2d8f419b.JPG)

Any possible solutions or advice would be appreciated. Any feedback regarding the issue itself would also be nice, was it clear? Would you have liked additional info?

**References:**
General datasheet MPU6000: https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf
Register datasheet MPU6000: https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Register-Map1.pdf
Datasheet of the MCU: https://www.st.com/resource/en/datasheet/stm32h743vi.pdf

**Comment by Mathijsvb** [comment]
Update: Still no communication. What I did find was a [board that's build around the MPU-6000](https://nl.rs-online.com/web/p/sensor-development-tools/8231892?cm_mmc=NL-PLA-DS3A-_-google-_-CSS_NL_EN_Raspberry_Pi_%26_Arduino_%26_Development_Tools_Whoop-_-(NL:Whoop!)+Sensor+Development+Tools-_-8231892&matchtype=&aud-826607889067:pla-342946028873&gclid=Cj0KCQjwgO2XBhCaARIsANrW2X2WVG-rK40a9kgocZ57SDbw3Vtzy6NJttUduof-A_meiEl0ifbyts0aAsdIEALw_wcB&gclsrc=aw.ds) with most pins exposed. If I succeed in communicating with it, I can find out whether I'm did something wrong or if the IC's are dead.

---
At the same time, I'm looking for a suitable replacement for the MPU-6000 since it's not recommended for new designs and the availability is bad. This is proving to be difficult since this type of IC is almost always out of stock. Some contenders:

* BNO055
* BMI088
* ISM330DHC
* LSM6DSOX
* MPU-6050 or ICM-20649 (These are  not recommended for new designs as well but if availability is good they could still make sense)
* ICM-40609-D (currently in production but not yet available)

**Comment by jurra** [comment]
Hi @Mathijsvb I can only give you feedback on the issue, is quite clear.

**Comment by Jerzeek** [comment]
Yeah the MPU-6050 seems mostly pin compatible, but you do lose the ability for SPI communication, I don't know how important speed is. maybe pop in one of these 6050's and see if you can get i2c communication working. then you know if it is the board or the chip

**Comment by Mathijsvb** [comment]
Hi @Jerzeek, thank you for the response. It's a good suggestion, and I would have been able to do this if I had not grounded the CS pin on the MPU-6000. This prevents being able to supply VLOGIC on the MPU-6050 (both pin 8 in the diagram). If I decide to use one of these, I'll definitely change this in a future revision of the board.

![Pasted image 20220829111521](https://user-images.githubusercontent.com/99826862/187168658-aba4a6d3-8725-4d03-ba6a-1a722a1945b7.png)

**Comment by Mathijsvb** [comment]
I'm back with an update. Attaching the [MPU-6000 based dev board](https://nl.rs-online.com/web/p/sensor-development-tools/8231892?cm_mmc=NL-PLA-DS3A-_-google-_-CSS_NL_EN_Raspberry_Pi_%26_Arduino_%26_Development_Tools_Whoop-_-(NL:Whoop!)+Sensor+Development+Tools-_-8231892&matchtype=&aud-826607889067:pla-342946028873&gclid=Cj0KCQjwgO2XBhCaARIsANrW2X2WVG-rK40a9kgocZ57SDbw3Vtzy6NJttUduof-A_meiEl0ifbyts0aAsdIEALw_wcB&gclsrc=aw.ds) discussed previously to the flight controller still yielded the same results of being unable to read out the WHO_AM_I register. So I took an entirely different microcontroller and attempted to read out the WHO_AM_I register again and it worked!

The difference between the two setups was that my test setup had a controllable CS pin, while the one in the flight controller was standard connected to ground. So what happens if we pull CS in the test setup standard low? Well, no response (and sometimes a gibberish response). 

![image](https://user-images.githubusercontent.com/99826862/218765578-04cb9541-4327-4830-bd03-b21cce8f3e59.png)

Searching around, it seems that some SPI devices need the CS transition to successfully manage communication and some don't. My best guess is that toggling CS is required for communication to remain in sync for the MPU-6000 (I was unable to find this detail in the datasheet, however). I'll close the issue for now.

This means a new board will need to be designed eventually after the other functionalities are tested.
